[#225] visualização da última métrica cadastrada
fga-eps-mds/2023-2-GEROcuidado-Front pull request #54
Opened 2023-12-11 23:13 UTC by martinsglucas

## Descrição

Corrige o bug do último valor da métrica que não estava sendo atualizado

## Issue

Closes [#225](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/issues/225)

## Tipos de Mudanças
 - [X] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [ ] Documentação
 - [ ] Experiência do usuário (UX)
 - [ ] Melhoria de desempenho

2023-12-11 23:48 UTC, pedro-cella approved these changes
Conserta o problema de carregamento das métricas na tela

2023-12-12 00:34 UTC, pedro-cella requested changes
Verificar se existem problemas na plataforma IOS

2023-12-13 00:07 UTC, HenriqueAmorim20 approved these changes

2023-12-13 00:08 UTC, HenriqueAmorim20 approved these changes

2023-12-13 00:35 UTC, merged